export const TODO_REQUEST = "TODO_REQUEST";
export const TODO_REQUEST_SUCCESS = "TODO_REQUEST_SUCCESS";
export const TODO_REQUEST_FAILED = "TODO_REQUEST_FAILED";

export const TODO_ADD_REQUEST = "TODO_ADD_REQUEST";
export const TODO_ADD_SUCCESS = "TODO_ADD_SUCCESS";
export const TODO_ADD_FAILED = "TODO_ADD_FAILED";

export const TODO_DELETE = "TODO_DELETE";
